# Generated by Django 5.0.2 on 2024-03-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_type',
            field=models.CharField(choices=[('NHS', 'NHS'), ('Private', 'Private')], default='NHS', max_length=7),
        ),
    ]
