# Generated by Django 5.0.2 on 2024-03-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_appointment_patient_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('recommended_daily_dosage', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhs_number', models.CharField(max_length=20)),
                ('relocation_date', models.DateField()),
                ('destination', models.CharField(max_length=255)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='requested_deletion',
            field=models.BooleanField(default=False),
        ),
    ]
