# Generated by Django 5.0.2 on 2024-03-26 00:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('patients', '0003_appointment_appointment_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='content_type',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='object_id',
            field=models.PositiveIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
